### ISSUE TITLE
Add Patch for net.ipv4.tcp_collapse_max_bytes (Improves high latency throughput)

### ISSUE THREAD

**Issue by SteveBox0** [xanmod/linux-patches#6]
Could you please consider adding the below patch to Xanmod? More information regarding this patch is available at the below blog post.

https://github.com/cloudflare/linux/blob/master/patches/0014-add-a-sysctl-to-enable-disable-tcp_collapse-logic.patch

https://blog.cloudflare.com/optimizing-tcp-for-high-throughput-and-low-latency/

**Comment by NovaAndrom3da** [comment]
My PR containing the patch was merged :)
